"""update foreign key constraints with CASCADE

Revision ID: 20bc31433d71
Revises: 187e06e62789
Create Date: 2025-09-17 22:15:40.531300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bc31433d71'
down_revision: Union[str, Sequence[str], None] = '187e06e62789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_ibfk_1'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reset_tokens_ibfk_1'), 'reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('reset_tokens_ibfk_1'), 'reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_ibfk_1'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
